Commit for features of Home Task 1, including different component types
pconnell99/epamReactApp pull request #1
Opened 2022-06-16 08:05 UTC by pconnell99

Built out three components for three widgets of the project, one function, two class.  Started styling the CSS a bit.

2022-06-17 22:05 UTC, Dmitry-White requested changes
Looks great!
Left a couple of comments for further improvements ;)

2022-06-17 22:05 UTC, Dmitry-White commented on src/GenreToggle.jsx
> +        return this.props.genres.map(genre => {
A couple of tips to improve readability and have a more robust JSX:
1. If the only thing you have in your function is a return statement - use short version
`genreItems = () => this.props.genres.map(...);`
2. Extract JS out of JSX, especially conditional statements
`const effectiveClassName =  this.state.chosenGenre === genre ? "genreItem selected" : "genreItem";`
3. When passing callbacks/arrow function as props - use short version
`onClick={() => this.handleChange(genre)}`

2022-06-20 08:50 UTC, pconnell99 commented on src/App.js
> +  let genres = ["All", "Documentary", "Comedy", "Horror", "Crime"];
My bad.  As I am the sole dev normally, I tend to dev 'knowing' that it is a constant.  Agreed, will remember.

2022-06-20 08:50 UTC, pconnell99 commented on src/App.js
> +      <GenreToggle genres={genres} onGenreSelected={(genre) => { alert(genre) }} />
Was purely for demonstration purposes of passing vars back up - would never use in production, agreed.

2022-06-20 08:51 UTC, pconnell99 commented on src/GenreToggle.jsx
> +    constructor(props) {
Ok.

2022-06-20 08:52 UTC, pconnell99 commented on src/GenreToggle.jsx
> +    genreItems = () => {
Agreed, I want as little JS manip. in render as I can get away with, MAYBE some ? in there, but that's about it.

2022-06-20 08:54 UTC, pconnell99 commented on src/GenreToggle.jsx
> +        return this.props.genres.map(genre => {
2. - Agreed, useful optimisation.
1 and 3. - Personal preference.  I find it more 'readable' when scanning code to have unambiguous scopes defined, even on single returns - but I'll of course follow any style guide available.

2022-06-23 09:24 UTC, merged